### ISSUE TITLE
网站是什么时候升级的？

### ISSUE THREAD

**Issue by hookind** [agefanscom/website#1]
![image](https://github.com/agefanscom/website/assets/42458265/894fa1ca-bcf2-45f4-b066-763df668e596)

想问下，网站是什么时候升级的？今天进来，发现变了一个模样，界面变美观了，但我之前收藏的动漫也不见了。

**Comment by agefanscom** [comment]
您好，收藏将于最迟晚上0点更新同步过来

古金 ***@***.***> 于 2023年7月5日周三 19:29写道：
