### ISSUE TITLE
部分网址证书被吊销

### ISSUE THREAD

**Issue by amehana92** [agefanscom/website#17]
相关网址：

> [https://www.agemys.org](https://www.agemys.org/?ref=github)

> [http://www.age.tv](http://www.age.tv/?ref=github)

> [http://www.agefans.com](http://www.agefans.com/?ref=github)

![msedge_Q0oS4J5d7a](https://github.com/user-attachments/assets/469d2a17-afde-4b64-a54b-1ed929a38311)

**Comment by agefanscom** [comment]
感謝反饋，今日由於 sectigo 部分證書被吊銷，已經再陸續更換，稍後將可以訪問！

**Comment by amehana92** [comment]
done
