### ISSUE TITLE
日本IP访问网页出错

### ISSUE THREAD

**Issue by xiaodu-frontend** [agefanscom/website#18]
<img width="1488" alt="スクリーンショット 2024-09-26 19 48 09" src="https://github.com/user-attachments/assets/10d9c7b1-7dc9-48ad-b0f1-fbfa28d6e0d3">

502报错，控制台显示403 Forbidden

**Comment by zxwwxz001** [comment]
俺也一样，是不是被ISP给ban了

**Comment by agefanscom** [comment]
由於日本版權問題，所以屏蔽了日本本土IP，對於無法訪問深表抱歉！

建議用以下方式訪問：

1. VPN軟體鏈接其他國家或者地區（除日韓外）
2. 本機域名 host 方式指定固定IP訪問 `23.224.60.155 agedm.org www.agedm.org m.agedm.org`，此方法以後如果更換域名和IP，需要一起更換
