### ISSUE TITLE
安卓的 APP 无法安装，手机型号是 realme

### ISSUE THREAD

**Issue by lieeew** [agefanscom/website#2]
![Screenshot_2023-08-09-07-54-15-94_d0f6572af797fe1d932039816ed9c9bc.jpg](https://github.com/agefanscom/website/assets/108205879/c3e0543e-444f-4691-a128-b148394522c5)

**Comment by lieeew** [comment]
解决了，把网关了就行了😂

**Comment by claviering** [comment]
工信部发布通知，明年4月起，不得为未备案的APP提供网络接入服务。开始要求所有APP都备案
