### ISSUE TITLE
重定向到反诈

### ISSUE THREAD

**Issue by dfmjndm** [agefanscom/website#6]
电信网络下，网站现在国内已经无法访问，或者被重定向到反诈
挂节点访问了网站，视频资源缺屏蔽海外ip，这什么弱智操作

**Comment by agefanscom** [comment]
定向到反詐頁面，可能是出於侵權的考慮

屏蔽海外資源很多資源站都是如此，如果不屏蔽，海外 DMCA 投訴會不堪其擾，目前能做的，只能更換有效域名，我們將近期更換新域名，以保證不會被大陸電信運營商屏蔽

感謝反饋！
