### ISSUE TITLE
易记域名失效

### ISSUE THREAD

**Issue by disorderk** [agefanscom/website#8]
![image](https://github.com/agefanscom/website/assets/53004320/81901419-bd44-4a0b-8be5-303a4d56fd46)
![image](https://github.com/agefanscom/website/assets/53004320/8b7c3b02-6f70-42e8-9e13-e44655cc8d6f)
~一直用的age.tv，今天消失了！

**Comment by HUGHNew** [comment]
age.tv : <https://cq.301jump.com:8989/?u=http://www.age.tv/&p=/>
网址解析跳转出错
